global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "faas-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["faas-gateway:2112"]
    scrape_interval: 5s

  - job_name: "faas-agent"
    metrics_path: /metrics
    static_configs:
      - targets: ["faas-agent:8080"]
    scrape_interval: 5s

  - job_name: "nats"
    metrics_path: /metrics
    static_configs:
      - targets: ["unified-storage:8222"]
    scrape_interval: 10s

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
